import type { Metadata } from "next";
import { Space_Grotesk, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { ThemeProvider } from "@/components/theme-provider";
import Link from "next/link";
import Image from "next/image";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Providers from "@/app/providers";
import HeaderUserButton from "@/components/header-user-button";
import { SelectProjects } from "@/components/select-projects";
import { Toaster } from "@/components/ui/sonner"
import AppHeader from "@/components/header";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Manije",
  description: "Generated by Nomad Prime",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${spaceGrotesk.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider
          appearance={{ baseTheme: dark }}
          waitlistUrl={"/waitlist"}
        >
          <Providers>
            <AppHeader />
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <main className="flex-1">
                {children}
              </main>
              <Toaster />
            </ThemeProvider>
          </Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}
