import type { Metadata } from "next";
import { Space_Grotesk, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { ThemeProvider } from "@/components/theme-provider";
import Link from "next/link";
import Image from "next/image";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Providers from "@/app/providers";
import HeaderUserButton from "@/components/header-user-button";
import { SelectProjects } from "@/components/select-projects";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Manije",
  description: "Generated by Nomad Prime",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${spaceGrotesk.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider
          appearance={{ baseTheme: dark }}
          waitlistUrl={"/waitlist"}
        >
          <Providers>
            <header className="flex justify-between items-center p-4 h-16 border-b gap-4">
              <Link
                href="/"
                className="text-xl font-semibold text-white hover:opacity-80 transition"
              >
                <Image
                  src="/logo_light.png"
                  alt="Manije logo"
                  width={28}
                  height={28}
                  priority
                  className="block dark:hidden"
                />
                <Image
                  src="/logo_dark.png"
                  alt="Manije logo"
                  width={28}
                  height={28}
                  priority
                  className="hidden dark:block"
                />
              </Link>
              <div className="flex flex-row items-start gap-4 flex-2">
                <SelectProjects />
              </div>
              <HeaderUserButton />
            </header>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}
